resources:
  database:
    type: postgres
  redis:
    type: redis

services:
  notifications-api:
    build: .
    port: 3000
    domain: api.notifications.codelitt.dev,slack-api.codelitt.dev
    resources:
      - database
      - redis
    environment:
      - LOG_ENV=
      - LOG_HOST=
      - SLACK_API_KEY
      - RAILS_ENV=development
      - SECRET_KEY_BASE=no-value
      - ADMIN_USER=
      - ADMIN_PASS=
  worker:
    build: .
    command: bundle exec sidekiq
    resources:
      - redis
      - postgres
