version: '2'
services:
  db:
    image: postgres
    container_name: notifications-db
    env_file:
      - .env
    ports:
      - '5432:5432'

    volumes:
      - .:/app

  redis:
    container_name: notifications-redis
    image: "redis:alpine"
    ports:
      - '6379:6379'

  app:
    container_name: notifications-api
    tty: true
    stdin_open: true
    build:
      context: .
      target: development

    volumes:
      - .:/app

    env_file:
      - .env

    ports:
      - '3000:3000'

    depends_on:
      - db
      - box
      - redis
      - sidekiq

    links:
      - db
      - box
      - redis
      - sidekiq

  sidekiq:
    container_name: notifications-sidekiq
    depends_on:
      - 'db'
      - 'redis'
      - box
    links:
      - box
    build:
      context: .
      target: development
    command: bundle exec sidekiq
    volumes:
      - '.:/app'
      - '/app/tmp' # don't mount tmp directory


  box:
    container_name: notifications-bundle-box
    image: busybox
    volumes:
      - /box
